### ISSUE TITLE
error running classification 2d - problem in comet_relion_submit.py line 325

### ISSUE THREAD

**Issue by monaw** [cianfrocco-lab/COSMIC-CryoEM-Gateway#137]
This error was displayed in the GUI when I tried to run a 2d classification job:

```
Wed Jan 16 13:42:08 PST 2019 > QUEUE : SUCCESS : NGBW-JOB-RELION_2D_CLASS_COMET-852A9B70E1B9433DAD3096A513815045 : Added to run queue. 
Wed Jan 16 13:42:17 PST 2019 > INPUTSTAGING : SUCCESS : NGBW-JOB-RELION_2D_CLASS_COMET-852A9B70E1B9433DAD3096A513815045 : Staging input files to COMET 
Wed Jan 16 13:42:17 PST 2019 > INPUTSTAGING : SUCCESS : NGBW-JOB-RELION_2D_CLASS_COMET-852A9B70E1B9433DAD3096A513815045 : Input files staged successfully 
Wed Jan 16 13:42:19 PST 2019 > SUBMITTING : ERROR : NGBW-JOB-RELION_2D_CLASS_COMET-852A9B70E1B9433DAD3096A513815045 : java.lang.Exception: Error submitting job: Traceback (most recent call last): File "/home/cosmic2/COSMIC-CryoEM-Gateway/remote_scripts/comet_relion_submit.py", line 325, in <module> relion_command,outdir,runhours,nodes,numiters,worksubdir=prepareRelionRun(args['commandline']) File "/home/cosmic2/COSMIC-CryoEM-Gateway/remote_scripts/comet_relion_submit.py", line 71, in prepareRelionRun newstarname='%s'%(starfiledirname)+'/'+'%s'%(inputZipFile.split('/')[-1]) UnboundLocalError: local variable 'starfiledirname' referenced before assignment 
```

**Comment by mcianfrocco** [comment]
Hi Mona,

I think this issue was due to your input star file not having the appropriate file structure, which means I need to check the file better for potential issues. 

That said, just for you and @kenneth59715 here is documentation for globus shared endpoints that have test particles and test 3D volume: 

https://docs.google.com/document/d/1I9LinZvbc1gcpYV6vKXFiqUCWWGAfWYDD4JEW4e6hAk/edit#heading=h.2vbvxcojvecl

**Comment by kenneth59715** [comment]
Michael,

 What are the parameters for the 2D test and 3D test?

Kenneth

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mcianfrocco** [comment]
Good point - I just added that to the google doc.

**Comment by kenneth59715** [comment]
I'm getting a submit error when trying 2D classification on job180/particles.star

Jan 17 2019 10:55:25 [read-2] DEBUG -        AsyncProcessRunner:210   [task=593, job=NGBW-JOB-RELION_2D_CLASS_COMET-595CA37473D04B979CD358039975ADC7] | Completed :  ssh -i /users/u2/cosmic2-gw/.ssh/id_rsa cosmic2@comet.sdsc.edu source /home/cosmic2/.bash_profile; export WB_JOBID=NGBW-JOB-RELION_2D_CLASS_COMET-595CA37473D04B979CD358039975ADC7; cd /projects/cosmic2/gateway/workspace/NGBW-JOB-RELION_2D_CLASS_COMET-595CA37473D04B979CD358039975ADC7/; comet_relion_submit.py --account TG-MCB170058 --url '-k https://cosmic2.sdsc.edu:8443/gateway/taskupdate.action?taskId=593\&jh=NGBW-JOB-RELION_2D_CLASS_COMET-595CA37473D04B979CD358039975ADC7' -- 'relion_refine_mpi --angpix 1 --offset_step 2 --psi_step 10 --iter 25 --particle_diameter 200 --K 50 --offset_range 5 --ctf --strict_highres_exp -1 --tau2_fudge 2 --i job180/particles.star '
Jan 17 2019 10:55:25 [read-2] DEBUG -      SSHExecProcessWorker:266   [task=593, job=NGBW-JOB-RELION_2D_CLASS_COMET-595CA37473D04B979CD358039975ADC7] | Returned:/projects/cosmic2/gateway/workspace/NGBW-JOB-RELION_2D_CLASS_COMET-595CA37473D04B979CD358039975ADC7
Could not find input star file

**Comment by mcianfrocco** [comment]
Hi @kenneth59715 - this is partially my fault - I shared the a directory that should have been slightly different. 

Try uploading data again from the shared globus endpoint to run 2D classification (since 3D analysis does not work, unless @monaw fixed this). Then upload the entire Extract/ directory and try again. I Just did this and it worked.

But, both your issue & Mona's issues highlight potential user-based input troubles that need to be handled better by the gateway. I'll work on these.
