### ISSUE TITLE
First time globus upload issue

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#185]
I saw the same error you showed above when I did my first transfer but then didn't see it again subsequently. Upon some debugging, it seems to appear the first time a user does a Globus transfer and the runtime error is

[...]
May 28 2019 20:37:29 [xec-14] ERROR -            TransferAction:895    |        Create directory: EndpointError(502 Bad Gateway) on request '62Gm5jkgN'         resource '/endpoint/de463f97-6d04-11e5-ba46-22000b92c6ec/mkdir': Endpoint       Error, Error (mkdir)
 Endpoint: XSEDE Comet (de463f97-6d04-11e5-ba46-22000b92c6ec)
 Server: oasis-dm.sdsc.xsede.org:2811
 Command: MKD /projects/cosmic2/gateway/globus_transfers/mcianfro@umich.edu/     testing20190528/
 Message: Fatal FTP Response
 ---
 Details: 550-GlobusError: v=1 c=PATH_NOT_FOUND\r\n550-GridFTP-Errno: 2\r\n550-  GridFTP-Reason: System error in mkdir\r\n550-GridFTP-Error-String: No such      file or directory\r\n550 End.\r\n
 
 May 28 2019 20:37:29 [xec-14] INFO  -               NgbwSupport:1009   |        mcianfro@umich.edu - Error, unable to access XSEDE Comet storage.
[...]
More debugging is needed to figure out why it fails first time...unfortunately looks like this WILL show for every user once. Might want to warn our beta testers...

**Comment by monaw** [comment]
tech note: The error comes from trying to create a directory whose parent directory doesn't exist.  This happens when the user does his/her first Globus transfer because the transfer is trying to create the folder/sub-directory when the user's main top-level Globus directory does not exist.  I've fixed the problem by creating the user top-level Globus transfer directory when the new Globus account is setup so now creating a subdirectory shouldn't cause a problem.

@mcianfrocco - I was able to test the creation of the user's top-level directory when logging in for the first time by using another account NOT linked with my current account.  However, I was unable to actually test the transfer because I don't have another endpoint to test with.  Would it be possible to have Yilai test creating account and doing a Globus upload transfer?

**Comment by mcianfrocco** [comment]
Yes - I'll have Yilai test this

**Comment by mcianfrocco** [comment]
Hi @monaw - I tried this with a different account and I got the same error

<img width="1159" alt="Screen Shot 2019-06-17 at 5 03 34 PM" src="https://user-images.githubusercontent.com/1464469/59636659-075d9580-9122-11e9-9349-8fd7e492a5da.png">

**Comment by monaw** [comment]
tech note - ok looks like java.io.File creates the user top-level directory with no group write permission which we need!  changed code to use java.nio.file.

@mcianfrocco - i just fixed this and also deleted your michael.a.cianfrocco@gmail.com account from database and globus transfer user data directory.  please give it another test...

**Comment by mcianfrocco** [comment]
Ok - just tried again and now I have a different error - it created a folder with my login name and I can't create any other folders. Although it seems like succeeds in creating the folder none show up

<img width="1112" alt="Screen Shot 2019-06-21 at 12 09 08 PM" src="https://user-images.githubusercontent.com/1464469/59936241-84885380-941d-11e9-8681-c13e4af49787.png">

**Comment by monaw** [comment]
yup, i see something weird, this account's directory permission isn't right:

`drwxr-x--- 2 cosmic2-gw cosmic2    0 Jun 21 09:08 michael.a.cianfrocco@gmail.com/`

it doesn't allow group write which is necessary; the correct permission should be:

`drwxrwx--- 2 cosmic2-gw cosmic2    0 Jun 20 19:06 046f34cb4b90efb0014d919e5f1b4ed9@ucsd.edu/`

not sure why your permission isn't correctly...still debugging...
