### ISSUE TITLE
Automated email RE: job submission / usage / statistics 

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#199]
-SUs per user total [per month]
-if users have 'excessive' amount of usage; sent email. If user goes above SU limit that is previously defined. 
-current available Sus to the XSEDE allocation

**Comment by kenneth59715** [comment]
I have a script in dev, usagecheck.py, that does some checks.
if any user has used more than build.properties:xsede_us_su_limit, print out user and usage
if show_accounts shows less than 200,000 SU, print out usage per user per month and
show_accounts output
if any output from the script, cron will email, otherwise no email.  From dev, this
only goes to kenneth. For production, we should put a good list of email addresses
into the crontab.

**Comment by kenneth59715** [comment]
This is running out of cron for cosmic2-gw on cosmic2.sdsc.edu
27 9 * * * /projects/cosmic2/gateway/scripts/usagecheck.py
