### ISSUE TITLE
Globus file handling

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#228]
Data handling for globus uploads: 

- If single file selected via Globus; upload into data list
- If more than one file; must have star file	
- If it doesn’t, then remove uploaded data and give user error message: “Error: We did not find any STAR files in your uploaded directory. No data have been uploaded.”

**Comment by monaw** [comment]
@mcianfrocco - do we allow a single file of any type or only one that ends in .mrc?

**Comment by mcianfrocco** [comment]
Any type for now.

**Comment by monaw** [comment]
tech note: need to update Transfer Status page to show OUR status, not Globus status because Globus may have successfully transferred multiple files but we consider the transfer failed if it does't contain at least 1 *.star file

**Comment by monaw** [comment]
Tech note, adding informative user messages for upload requires some refactoring to keep track of files, directories and each status as well as reason why each failed.  Additionally, previously the logic is to get the status from Globus, then update our database.  But now since our status may be different than Globus' status, we need to get Globus status, update our database and then get the info from our database (not Globus).

**Comment by monaw** [comment]
@mcianfrocco - ok, I've updated our Globus handling and added displaying of user messages that's hopefully helpful.  Here are some screenshot examples:

![Screen Shot 2020-02-20 at 10 37 15 AM](https://user-images.githubusercontent.com/18472048/75005608-ce4d9180-5423-11ea-976e-51d47aa87db2.png)

![Screen Shot 2020-02-20 at 9 10 17 PM](https://user-images.githubusercontent.com/18472048/75006096-6f891780-5425-11ea-8180-8452d1acef4c.png)

Let me know if you'd like to show different info and/or different message...

**Comment by monaw** [comment]
update has been pushed to production
