### ISSUE TITLE
Refresh between when a job finishes to when it is marked as 'complete' on the gateway

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#270]
Hi @kenneth59715 - 

is there a refresh time set somewhere for how often the task refreshes to check for output files? What is it? It seems slightly long - 5 minutes?

**Comment by kenneth59715** [comment]
This might be in build.properties as
checkJobs.poll.seconds
But the job script is supposed to send a curl command to the portal
to notify on job completion...
curl <task url>\&status=done

**Comment by kenneth59715** [comment]
The curl command in the slurm job script is something like this:
curl %s\&status=DONE\n" %  url

where url is the --url given to the submit program.

**Comment by mcianfrocco** [comment]
To follow up on this, job on production named "COSMIC2-JOB-RELION_2D_CLASS_COMET-CF9F4459483D4CA1A9534FDCC1F7A948" finished at 8:06 AM on Comet and the email was sent to me at 8:52 AM. The job was marked as finished on the gateway within a few minutes of the job finishing on Comet. 

Is this what would be fixed with your curl command @kenneth59715 ?

**Comment by kenneth59715** [comment]
I don't think the curl command would help with that delay, since the
portal already knows the job completed. From the loadResults.log,
the portal sent email at 8:09am, so the delay is somewhere in the
mail system:

Sep 17 2020 08:09:21 [read-1] DEBUG - TaskMonitor:339 [task=235, job=COSMIC2-JOB-RELION_2D_CLASS_COMET-CF9F4459483D4CA1A9534FDCC1F7A948] | In notify job complete, email is mcianfro@umich.edu
Sep 17 2020 08:09:21 [read-1] DEBUG - JobCompleteEvent:135 [task=235, job=COSMIC2-JOB-RELION_2D_CLASS_COMET-CF9F4459483D4CA1A9534FDCC1F7A948] | Sending job completion email for cipres portal user to mcianfro@umich.edu

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by kenneth59715** [comment]
@mcianfrocco

One thing you can look at is the detailed header of the notification email.
That should have a timestamp for every email relay between cosmic2 and
your mail server. I took a look at one of mine from yesterday, and there
was not a long delay in my header chain.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
