### ISSUE TITLE
Large globus transfer 

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#32]
Hi @monaw @cdesyoun - I did a large globus transfer last night which essentially worked - 1176 out of 1178 files were transferred which is 2.33 TB. The transfer wasn't 100% successful, only because I think that two temporary files that were being created on my local server were included in the list of files to move, and then, when they were deleted b/c they were temporary, Globus got hung up on trying to find it.

I'll do a transfer again today on a directory that does not have files being written to it - I'm surprised that this was a problem. 

Mike

Here are the errors in case you were wondering:

First error: 'Operation timed out'

```
{
"context": [
{
"endpoint": "XSEDE Comet (de463f97-6d04-11e5-ba46-22000b92c6ec)",
"operation": "File Transfer - Capability Check"
}
],
"error": {
"details": "Error (connect)\nEndpoint: XSEDE Comet (de463f97-6d04-11e5-ba46-22000b92c6ec)\nServer: oasis-dm.sdsc.xsede.org:2811\nMessage: The operation timed out\n",
"type": "GSHError"
}
}
```

Second error: No such file or directory

```
Error (transfer)
Endpoint: Leonora (caea9c7c-3216-11e7-bcb9-22000b9a448b)
Server: Globus Connect
File: /data/microscopes/frames/17may04a/rawdata/.17may04a_gb4_gr3_00009gr_00014sq_00090hl_v01_00002en.frames.mrc.jpkMek
Command: MLST /data/microscopes/frames/17may04a/rawdata/.17may04a_gb4_gr3_00009gr_00014sq_00090hl_v01_00002en.frames.mrc.jpkMek
Message: Fatal FTP response
---
Details: 500-Command failed : System error in stat: No such file or directory\r\n500-A system call failed: No such file or directory\r\n500 End.\r\n

```

**Comment by mcianfrocco** [comment]
Second try worked! 1.07 TB transferred : )

<img width="862" alt="success" src="https://cloud.githubusercontent.com/assets/1464469/25775129/c95126ba-3252-11e7-8e0a-02a28b22fba4.png">

**Comment by cdesyoun** [comment]
Hi @mcianfrocco , that is the reason that we need to test a lot since we are not managing globus server locally. Sometimes, cloud services like globus seems a little bit convenient to use. But, it is very hard to debug problems. 

In order to get your tasks in more detail, please log into the globus page, https://www.globus.org/.
Like the below page, please click "Activity" link for see your tasks.

In order to change your display name for endpoints, please click "Endpoints" link.

![screen shot 2017-05-07 at 9 57 33 pm](https://cloud.githubusercontent.com/assets/10523370/25790756/3891271e-3370-11e7-9388-c0d12f981acd.jpg)
