### ISSUE TITLE
Log in error (temporary)

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#33]
Hi @monaw - today (5/6) when I tried logging into the gateway I would get this error message (see image). But, when I click 'Home' > 'Log in' (a second time), then I'm able to log in successfully. 

Not a fatal problem, but wanted to report it.

<img width="1088" alt="errror" src="https://cloud.githubusercontent.com/assets/1464469/25774511/056b205a-3245-11e7-926f-d053796087ed.png">

**Comment by cdesyoun** [comment]
Hi @mcianfrocco , I guess as the default setting, MySQL running on SDSC seems to have an 8 hour time out on its connections. We are running cosmic2 WAR in Tomcat utilizing Hibernate for ORM. So, after around 8 hours (i.e. overnight), sometimes, I got broken pipes when it picks up an idle connection on this cosmic2 portal. When this happened, that error page was given because of communication link failure between portal server and mySQL server.
Tuning the properties in the hibernate configuration file, I am trying to fix this issue with Mona. It seems it is not working very well. 
I will try to reconfigure properties in this file. If not working it, maybe I will need to contact SDSC system admin to manage MySQL server that can change properties in my.cnf file.

**Comment by mcianfrocco** [comment]
Is it possible to programmatically log user out when this happens? Then error would go away. @cdesyoun will look into this.

**Comment by cdesyoun** [comment]
Hi Mike, Mona,

I did update the configuration for solving this issue.
Please report it when you got that error.

Thanks,
Choonhan Youn
